// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCko8jgQdmBUfTCPfuQHJ9w1DRPGQLKsI8',
    appId: '1:28497021377:web:d162167a5b820a2dd74740',
    messagingSenderId: '28497021377',
    projectId: 'restaurant-117',
    authDomain: 'restaurant-117.firebaseapp.com',
    storageBucket: 'restaurant-117.appspot.com',
    measurementId: 'G-7G3X811TGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8lgr-TaExcigxNNTddlxthm9oiZYegU',
    appId: '1:28497021377:android:7bb8b0008951a0e7d74740',
    messagingSenderId: '28497021377',
    projectId: 'restaurant-117',
    storageBucket: 'restaurant-117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvAD0dniC535EYo4rJ2fhlVBluuGEBWJg',
    appId: '1:28497021377:ios:80bfe91651a9adacd74740',
    messagingSenderId: '28497021377',
    projectId: 'restaurant-117',
    storageBucket: 'restaurant-117.appspot.com',
    iosClientId: '28497021377-5du4rqriqc63bbekaers1fu4vovl55lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantios',
  );
}
